# ----------------------------------------------------------------
# Source:
#   https://jupyterlab.readthedocs.io/en/stable/user/rtc.html
#
# HOW TO RUN:
#   docker compose up -d
# ----------------------------------------------------------------
services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    # Always restart the container, even after reboot
    restart: always
    ports:
      - 80:8888
    volumes:
      # Location of the volume:
      #   /var/lib/docker/volumes/...
      - jupyter-data:/home/jovyan
    entrypoint:
      - jupyter
      - lab
      - --collaborative
      - --no-browser
      - --NotebookApp.token=''
      - --NotebookApp.password=''
      - --ip
      - "*"

volumes:
  jupyter-data:
