# ----------------------------------------------------------------
# WHAT IS THIS FILE FOR?
# Experimental Jupyter Lab server. Work in progress.
#
# HOW TO RUN:
#   docker compose up -d
#
#   # Run this only the first time you run.
#   # Skip these after the first time.
#   docker exec -it jupyter sh
#   jupyter lab password
#   <Set the Jupyter access password>
#   <Press ctrl + d to exit the docker process>
#   docker compose down
#   docker compose up -d
# ----------------------------------------------------------------
services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    # Always restart the container, even after reboot
    restart: always
    ports:
      - 80:8888
    volumes:
      # Location of the volume:
      #   /var/lib/docker/volumes/...
      - jupyter-data:/home/jovyan
    entrypoint:
      - jupyter
      - lab
      - --no-browser
      - --ip
      - "*"

volumes:
  jupyter-data:
