#! /bin/bash

# ------------------------------------------------------
# Run a Jupyter Lab. By default, all ipynb files are
# stored inside /home/jovyan
# Source:
#   https://hub.docker.com/r/jupyter/datascience-notebook
# ------------------------------------------------------
docker run -it --rm -p 80:8888 -v jupyter-data:/home/jovyan jupyter/datascience-notebook sh

# Set a password
jupyter lab password

# Start Jupyter Lab with real time collaboration enabled.
# "Following Jupyter Notebook notice,
# [Jupyter Notebook Deprecation Notice:
#   https://github.com/jupyter/notebook#noticeJupyterLab
# ] JupyterLab is now the default for all the Jupyter Docker
# stack images."
# Source:
#   https://github.com/jupyter/docker-stacks
jupyter lab --collaborative
